version: '4.18.0'

services:

  react_frontend_ifm:
    build: ./react_frontend_ifm
    container_name: frontend_c
    stdin_open: true
    tty: true
    network_mode: "host"

  javaee_backend_ifm:
    build: ./javaee_backend_ifm
    container_name: backend_c
    stdin_open: true
    tty: true
    network_mode: "host"

  jms_rabbitmq_ifm:
    build: ./jms_rabbitmq_ifm
    container_name: jms_c
    stdin_open: true
    tty: true
    network_mode: "host"

